### PR TITLE
feat: Enable providing root directory to GUI app via command-line or drag-and-drop

### PR DESCRIPTION
**Pull request by mwanchap**
For issue #36. Added feature to check path lengths for directories dropped onto PathLengthCheckerGUI.exe or passed via the command line.

Future idea: allow multiple directories, and support the same argument syntax as PathLengthChecker.exe, maybe using Program.ParseArgs

### CODE REVIEW

**Comment by deadlydog** [comment]
Thanks for the contribution! Just curious if you're part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/) yet @mwanchap ? If you sign up this can count towards one of your 4 PRs :)  I'll wait until you response before merging in. Thanks for the contribution!

**Comment by mwanchap** [comment]
Whoa, I wasn't expecting a reply so quickly! And yes, I'm already signed up. I actually found this repo by exploring the hacktoberfest tag

**Comment by deadlydog** [comment]
Thanks again for contributing! This was something I hadn't yet taken the time to Google to figure out how to do, but you showed me in this PR 👍

**Comment by mwanchap** [comment]
I'll tell you a secret: I didn't know how to do it either 😅

**Pull request merged**
