### PR TITLE
Continue after exception on enumeration

### LINKED ISSUE #1: Option to automatically skip private folders
If I'm searching inside a folder ("A") that has 5 sub-folders (1, 2, 3, 4, 5) and I don't have access to 3, the search within A fails and shows, "Access to the path 'xx' is denied."

This requires me to manually enter the 1, 2, 4 and 5 folder paths into the program ton continue.

Could there be an option in v1.1.2 to automatically skip private folders and continue searching?

Fantastic program, @deadlydog, by the way.

### LINKED ISSUE #2: Skip non-accessible folders
When I run PathLengthChecker over the whole partiton D: of my 64bit Win 7 system and the prgm comes to the system folder "System Volume Information" it pops up an error

"Cannot access System Volume Information"

and aborts.

Next release of PathLengthChecker should automatically skip these kind of folder.

Ben

### LINKED ISSUE #3: Show progress indicator/number of already processed files
When I run PathLengthChecker over the whole partiton D: of my 64bit Win 7 system then the run lasts very long since there are many, many files.

To give the user a rough estimation about the already done work PathLengthCehcker should show
either a percentage value or number of already processed files or file name of currently investigated files (if processing in alphabetical sort order).

Can you implement it in the next release?

Ben

### PR DESCRIPTION
**Pull request by A9G-Data-Droid**
I have used AlphaFS to enumerate filesystem objects skipping access denied errors.

Add async tasks to avoid locking the UI thread while searching. This allows us to update the UI with results as they are found.
Update all projects to Framework version 4.8
Update all NuGet packages to latest versions

 - Closes #1
 - Closes #2
 - Closes #3

### CODE REVIEW

**Comment by A9G-Data-Droid** [comment]
It's possible the tests will need to be rewritten. For example, we no longer throw exceptions. If you cite an invalid directory it will return no results instead of an exception.

**Comment by deadlydog** [comment]
Awesome, thanks so much for taking the time to write up this PR @A9G-Data-Droid :) I'll try and review the change in more detail in the next couple of days. My initial hesitation to merging this PR as-is is the bump to .Net Framework 4.8. Unless it's required for some new functionality, we should try to target lower .Net Framework versions, since this is an app that runs on the client's machine, not on our own servers where we easily control the .Net Framework version installed. Bumping to .Net Framework 4.8 unnecessarily means that the app would no longer be usable by as wide of an audience.

That said, if the bump is actually required to make the new functionality work, I can look at bumping the major version number of the app and offering 2 versions of it; one for older .Net Framework versions and one for newer ones.

Also, in regards to your commit message "We need to update to .NET Core now"; .Net 5 is scheduled to come out soon, so we can likely skip ".Net Core" and jump straight to .Net 5 when the time comes :)

Again, thanks for taking the time to improve this app 👍

**Comment by A9G-Data-Droid** [comment]
@deadlydog The minimum Windows version for Framework 4.8 is Windows 7 SP1, which went EOL in January. I see no reason why the client wouldn't have 4.8 installed. It's installed automatically by default by Windows Update. I tend to update Framework and NuGet libraries every time I push a new version because of the performance improvements I see. Sometimes it is significant. In this case, the move to AlphaFS actually made the performance worse but it was the easiest way to get past all the exceptions. It also has code to better handle long filenames. 

I tried to move to .NET core and failed because of the NuGet dependencies requiring Framework.

When you are comfortable moving to .NET 5 you could use the new options to ignore exceptions in EnumerateFileSystem entries and remove AlphaFS. This might result in better performance and is worth a try.

**Comment by deadlydog** [comment]
I just pulled down the PR and did a quick test, and it looks like it accidentally breaks the paths and reports the wrong values. Old app is on the left, the PR app is on the right in the screenshot.
image

**Comment by A9G-Data-Droid** [comment]
So it does.

**Comment by deadlydog** [comment]
I've fixed up the issues. Thanks again for contributing @A9G-Data-Droid 👍 :D

**Pull request merged**
